# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns a test landscape.
#'
#' @param nItems How many items.
#' @param landsize Size as a numeric (float).
#' @param nClusters How many clusters, an integer value.
#' @param clusterSpread Dispersal of items around cluster centres.
#' @param regen_time Regeneration time, in timesteps.
#' @param p_type Proportion of type 1.
#' @return A data frame of the evolved population traits.
get_test_landscape <- function(nItems, landsize, nClusters, clusterSpread, regen_time, p_type) {
    .Call(`_ecoevomove3_get_test_landscape`, nItems, landsize, nClusters, clusterSpread, regen_time, p_type)
}

#' Runs an exploitation competition simulation returning structured output.
#'
#' @description Run the simulation using parameters passed as
#' arguments to the corresponding R function.
#'
#' @param scenario The scenario: 0 for random movement, 1 for optimal movement,
#' 2 for evolved mechanistic movement.
#' @param popsize The population size.
#' @param nItems How many food items on the landscape.
#' @param p_type Proportion of items of type 1.
#' @param landsize The size of the landscape as a numeric (double).
#' @param nClusters Number of clusters around which food is generated.
#' @param clusterSpread How dispersed food is around the cluster centre.
#' @param tmax The number of timesteps per generation.
#' @param genmax The maximum number of generations per simulation.
#' @param range_perception The movement range for agents.
#' @param handling_time The handling time.
#' @param regen_time The item regeneration time.
#' @param nThreads How many threads to parallelise over. Set to 1 to run on
#' the HPC Peregrine cluster.
#' @param dispersal A float value; the standard deviation of a normal
#' distribution centred on zero, which determines how far away from its parent
#' each individual is initialised. The standard value is 5 percent of the
#' landscape size (\code{landsize}), and represents local dispersal.
#' Setting this to 10 percent is already almost equivalent to global dispersal.
#' @param mProb The probability of mutation. The suggested value is 0.01.
#' While high, this may be more appropriate for a small population; change this
#' value and \code{popsize} to test the simulation's sensitivity to these values.
#' @param mSize Controls the mutational step size, and represents the scale
#' parameter of a Cauchy distribution. 
#' @return An S4 class, `pathomove_output`, with simulation outcomes.
run_model <- function(popsize, scenario, nItems, p_type, landsize, nClusters, clusterSpread, handling_time, regen_time, tmax, genmax, range_perception, range_move, dispersal, nThreads, mProb, mSize) {
    .Call(`_ecoevomove3_run_model`, popsize, scenario, nItems, p_type, landsize, nClusters, clusterSpread, handling_time, regen_time, tmax, genmax, range_perception, range_move, dispersal, nThreads, mProb, mSize)
}

